[sources.chess]
secret_str = "secret_str" # please set me up!

[sources.chess.secret_dict] # please set me up!
key = "value"

[destination.filesystem]
bucket_url = "s3://warehouse" # please set me up!

[destination.filesystem.credentials]
aws_access_key_id = "your_key" # please set me up!
aws_secret_access_key = "your_key" # please set me up!
endpoint_url = "http://localhost:9000"
